import { CharasData } from "@/types/ba-chara-data";

export const CHARA_DATA: CharasData = {
  ハレ: {
    charaName: "ハレ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハレ.png",
  },
  "ハルカ（正月）": {
    charaName: "ハルカ（正月）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハルカ（正月）.png",
  },
  "カズサ（バンド）": {
    charaName: "カズサ（バンド）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カズサ（バンド）.png",
  },
  ハルナ: {
    charaName: "ハルナ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハルナ.png",
  },
  "カンナ（水着）": {
    charaName: "カンナ（水着）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カンナ（水着）.png",
  },
  コハル: {
    charaName: "コハル",
    equip3: "ネックレス",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コハル.png",
  },
  ツバキ: {
    charaName: "ツバキ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ツバキ.png",
  },
  レンゲ: {
    charaName: "レンゲ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/レンゲ.png",
  },
  "ヒナ（水着）": {
    charaName: "ヒナ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒナ（水着）.png",
  },
  ムツキ: {
    charaName: "ムツキ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ムツキ.png",
  },
  サツキ: {
    charaName: "サツキ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サツキ.png",
  },
  ミドリ: {
    charaName: "ミドリ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミドリ.png",
  },
  "シロコ（水着）": {
    charaName: "シロコ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シロコ（水着）.png",
  },
  食蜂操祈: {
    charaName: "食蜂操祈",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/食蜂操祈.png",
  },
  ミナ: {
    charaName: "ミナ",
    equip3: "お守り",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミナ.png",
  },
  コトリ: {
    charaName: "コトリ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コトリ.png",
  },
  "フウカ（正月）": {
    charaName: "フウカ（正月）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/フウカ（正月）.png",
  },
  ヨシミ: {
    charaName: "ヨシミ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヨシミ.png",
  },
  "アコ（ドレス）": {
    charaName: "アコ（ドレス）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アコ（ドレス）.png",
  },
  チナツ: {
    charaName: "チナツ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チナツ.png",
  },
  "サキ（水着）": {
    charaName: "サキ（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サキ（水着）.png",
  },
  アカリ: {
    charaName: "アカリ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アカリ.png",
  },
  ツクヨ: {
    charaName: "ツクヨ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ツクヨ.png",
  },
  "コハル（水着）": {
    charaName: "コハル（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コハル（水着）.png",
  },
  イブキ: {
    charaName: "イブキ",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イブキ.png",
  },
  フウカ: {
    charaName: "フウカ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/フウカ.png",
  },
  ツルギ: {
    charaName: "ツルギ",
    equip3: "お守り",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ツルギ.png",
  },
  ワカモ: {
    charaName: "ワカモ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ワカモ.png",
  },
  トモエ: {
    charaName: "トモエ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/トモエ.png",
  },
  "イズナ（水着）": {
    charaName: "イズナ（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イズナ（水着）.png",
  },
  "アズサ（水着）": {
    charaName: "アズサ（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アズサ（水着）.png",
  },
  "ハナコ（水着）": {
    charaName: "ハナコ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハナコ（水着）.png",
  },
  スミレ: {
    charaName: "スミレ",
    equip3: "お守り",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/スミレ.png",
  },
  "アル（正月）": {
    charaName: "アル（正月）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アル（正月）.png",
  },
  "ミネ（アイドル）": {
    charaName: "ミネ（アイドル）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミネ（アイドル）.png",
  },
  キサキ: {
    charaName: "キサキ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/キサキ.png",
  },
  "ヒヨリ（水着）": {
    charaName: "ヒヨリ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒヨリ（水着）.png",
  },
  "ホシノ（水着）": {
    charaName: "ホシノ（水着）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ホシノ（水着）.png",
  },
  ノノミ: {
    charaName: "ノノミ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ノノミ.png",
  },
  チセ: {
    charaName: "チセ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チセ.png",
  },
  "アツコ（水着）": {
    charaName: "アツコ（水着）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アツコ（水着）.png",
  },
  "ノドカ（温泉）": {
    charaName: "ノドカ（温泉）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ノドカ（温泉）.png",
  },
  エイミ: {
    charaName: "エイミ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/エイミ.png",
  },
  ミカ: {
    charaName: "ミカ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミカ.png",
  },
  セイア: {
    charaName: "セイア",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セイア.png",
  },
  アル: {
    charaName: "アル",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アル.png",
  },
  ユカリ: {
    charaName: "ユカリ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ユカリ.png",
  },
  イオリ: {
    charaName: "イオリ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イオリ.png",
  },
  ミヤコ: {
    charaName: "ミヤコ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミヤコ.png",
  },
  "セリナ（クリスマス）": {
    charaName: "セリナ（クリスマス）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セリナ（クリスマス）.png",
  },
  シュン: {
    charaName: "シュン",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シュン.png",
  },
  "ウタハ（応援団）": {
    charaName: "ウタハ（応援団）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ウタハ（応援団）.png",
  },
  "エイミ（水着）": {
    charaName: "エイミ（水着）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/エイミ（水着）.png",
  },
  "トキ（バニーガール）": {
    charaName: "トキ（バニーガール）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/トキ（バニーガール）.png",
  },
  佐天涙子: {
    charaName: "佐天涙子",
    equip3: "ネックレス",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/佐天涙子.png",
  },
  "ミモリ（水着）": {
    charaName: "ミモリ（水着）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミモリ（水着）.png",
  },
  "ツルギ（水着）": {
    charaName: "ツルギ（水着）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ツルギ（水着）.png",
  },
  サヤ: {
    charaName: "サヤ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サヤ.png",
  },
  "チェリノ（温泉）": {
    charaName: "チェリノ（温泉）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チェリノ（温泉）.png",
  },
  "シグレ（温泉）": {
    charaName: "シグレ（温泉）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シグレ（温泉）.png",
  },
  アズサ: {
    charaName: "アズサ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アズサ.png",
  },
  "イオリ（水着）": {
    charaName: "イオリ（水着）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イオリ（水着）.png",
  },
  モエ: {
    charaName: "モエ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/モエ.png",
  },
  御坂美琴: {
    charaName: "御坂美琴",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/御坂美琴.png",
  },
  フィーナ: {
    charaName: "フィーナ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/フィーナ.png",
  },
  "カヨコ（正月）": {
    charaName: "カヨコ（正月）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カヨコ（正月）.png",
  },
  "ヨシミ（バンド）": {
    charaName: "ヨシミ（バンド）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヨシミ（バンド）.png",
  },
  トキ: {
    charaName: "トキ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/トキ.png",
  },
  イズナ: {
    charaName: "イズナ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イズナ.png",
  },
  マキ: {
    charaName: "マキ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マキ.png",
  },
  アスナ: {
    charaName: "アスナ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アスナ.png",
  },
  メル: {
    charaName: "メル",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/メル.png",
  },
  "アスナ（制服）": {
    charaName: "アスナ（制服）",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アスナ（制服）.png",
  },
  "マリー（アイドル）": {
    charaName: "マリー（アイドル）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マリー（アイドル）.png",
  },
  "ヒナ（ドレス）": {
    charaName: "ヒナ（ドレス）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒナ（ドレス）.png",
  },
  カホ: {
    charaName: "カホ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カホ.png",
  },
  レイサ: {
    charaName: "レイサ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/レイサ.png",
  },
  マリー: {
    charaName: "マリー",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マリー.png",
  },
  "シロコ（ライディング）": {
    charaName: "シロコ（ライディング）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シロコ（ライディング）.png",
  },
  "ワカモ（水着）": {
    charaName: "ワカモ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ワカモ（水着）.png",
  },
  ミモリ: {
    charaName: "ミモリ",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミモリ.png",
  },
  "フブキ（水着）": {
    charaName: "フブキ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/フブキ（水着）.png",
  },
  "ミドリ（メイド）": {
    charaName: "ミドリ（メイド）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミドリ（メイド）.png",
  },
  "ユウカ（体操服）": {
    charaName: "ユウカ（体操服）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ユウカ（体操服）.png",
  },
  リオ: {
    charaName: "リオ",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/リオ.png",
  },
  アツコ: {
    charaName: "アツコ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アツコ.png",
  },
  サキ: {
    charaName: "サキ",
    equip3: "ネックレス",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サキ.png",
  },
  カヨコ: {
    charaName: "カヨコ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カヨコ.png",
  },
  "セリカ（水着）": {
    charaName: "セリカ（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セリカ（水着）.png",
  },
  カズサ: {
    charaName: "カズサ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カズサ.png",
  },
  ハナコ: {
    charaName: "ハナコ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハナコ.png",
  },
  "コタマ（キャンプ）": {
    charaName: "コタマ（キャンプ）",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コタマ（キャンプ）.png",
  },
  シグレ: {
    charaName: "シグレ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シグレ.png",
  },
  ヒナ: {
    charaName: "ヒナ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒナ.png",
  },
  "チセ（水着）": {
    charaName: "チセ（水着）",
    equip3: "ネックレス",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チセ（水着）.png",
  },
  "ムツキ（正月）": {
    charaName: "ムツキ（正月）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ムツキ（正月）.png",
  },
  カリン: {
    charaName: "カリン",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カリン.png",
  },
  イロハ: {
    charaName: "イロハ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イロハ.png",
  },
  "アスナ（バニーガール）": {
    charaName: "アスナ（バニーガール）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アスナ（バニーガール）.png",
  },
  ハスミ: {
    charaName: "ハスミ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハスミ.png",
  },
  モモイ: {
    charaName: "モモイ",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/モモイ.png",
  },
  "モエ（水着）": {
    charaName: "モエ（水着）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/モエ（水着）.png",
  },
  イチカ: {
    charaName: "イチカ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イチカ.png",
  },
  "ネル（制服）": {
    charaName: "ネル（制服）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ネル（制服）.png",
  },
  "ホシノ（臨戦）": {
    charaName: "ホシノ（臨戦）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ホシノ（臨戦）.png",
  },
  "ヒフミ（水着）": {
    charaName: "ヒフミ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒフミ（水着）.png",
  },
  アヤネ: {
    charaName: "アヤネ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アヤネ.png",
  },
  ミユ: {
    charaName: "ミユ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミユ.png",
  },
  "ユウカ（パジャマ）": {
    charaName: "ユウカ（パジャマ）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ユウカ（パジャマ）.png",
  },
  シミコ: {
    charaName: "シミコ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シミコ.png",
  },
  "シロコ＊テラー": {
    charaName: "シロコ＊テラー",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シロコ＊テラー.png",
  },
  ジュンコ: {
    charaName: "ジュンコ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ジュンコ.png",
  },
  初音ミク: {
    charaName: "初音ミク",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/初音ミク.png",
  },
  "トモエ（チーパオ）": {
    charaName: "トモエ（チーパオ）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/トモエ（チーパオ）.png",
  },
  "ユズ（メイド）": {
    charaName: "ユズ（メイド）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ユズ（メイド）.png",
  },
  ノア: {
    charaName: "ノア",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ノア.png",
  },
  マコト: {
    charaName: "マコト",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マコト.png",
  },
  "サクラコ（アイドル）": {
    charaName: "サクラコ（アイドル）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サクラコ（アイドル）.png",
  },
  マシロ: {
    charaName: "マシロ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マシロ.png",
  },
  "カリン（制服）": {
    charaName: "カリン（制服）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カリン（制服）.png",
  },
  "ジュンコ（正月）": {
    charaName: "ジュンコ（正月）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ジュンコ（正月）.png",
  },
  "ネル（バニーガール）": {
    charaName: "ネル（バニーガール）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ネル（バニーガール）.png",
  },
  チアキ: {
    charaName: "チアキ",
    equip3: "お守り",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チアキ.png",
  },
  "ハスミ（体操服）": {
    charaName: "ハスミ（体操服）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハスミ（体操服）.png",
  },
  マリナ: {
    charaName: "マリナ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マリナ.png",
  },
  キリノ: {
    charaName: "キリノ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/キリノ.png",
  },
  カンナ: {
    charaName: "カンナ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カンナ.png",
  },
  ミネ: {
    charaName: "ミネ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミネ.png",
  },
  カスミ: {
    charaName: "カスミ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カスミ.png",
  },
  "アヤネ（水着）": {
    charaName: "アヤネ（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アヤネ（水着）.png",
  },
  "アイリ（バンド）": {
    charaName: "アイリ（バンド）",
    equip3: "お守り",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アイリ（バンド）.png",
  },
  チェリノ: {
    charaName: "チェリノ",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チェリノ.png",
  },
  ヒヨリ: {
    charaName: "ヒヨリ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒヨリ.png",
  },
  ミチル: {
    charaName: "ミチル",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミチル.png",
  },
  "ハナエ（クリスマス）": {
    charaName: "ハナエ（クリスマス）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハナエ（クリスマス）.png",
  },
  チヒロ: {
    charaName: "チヒロ",
    equip3: "ネックレス",
    equip1: "帽子",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チヒロ.png",
  },
  ウイ: {
    charaName: "ウイ",
    equip3: "お守り",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ウイ.png",
  },
  "シュン（幼女）": {
    charaName: "シュン（幼女）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シュン（幼女）.png",
  },
  ナギサ: {
    charaName: "ナギサ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ナギサ.png",
  },
  ハルカ: {
    charaName: "ハルカ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハルカ.png",
  },
  "モモイ（メイド）": {
    charaName: "モモイ（メイド）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/モモイ（メイド）.png",
  },
  キキョウ: {
    charaName: "キキョウ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/キキョウ.png",
  },
  ミノリ: {
    charaName: "ミノリ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミノリ.png",
  },
  ホシノ: {
    charaName: "ホシノ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ホシノ.png",
  },
  ネル: {
    charaName: "ネル",
    equip3: "お守り",
    equip1: "帽子",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ネル.png",
  },
  ウタハ: {
    charaName: "ウタハ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ウタハ.png",
  },
  ユウカ: {
    charaName: "ユウカ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ユウカ.png",
  },
  ヒビキ: {
    charaName: "ヒビキ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒビキ.png",
  },
  "カヨコ（ドレス）": {
    charaName: "カヨコ（ドレス）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カヨコ（ドレス）.png",
  },
  ヒナタ: {
    charaName: "ヒナタ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒナタ.png",
  },
  アイリ: {
    charaName: "アイリ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アイリ.png",
  },
  ルミ: {
    charaName: "ルミ",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ルミ.png",
  },
  メグ: {
    charaName: "メグ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/メグ.png",
  },
  スズミ: {
    charaName: "スズミ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/スズミ.png",
  },
  ヒフミ: {
    charaName: "ヒフミ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒフミ.png",
  },
  アコ: {
    charaName: "アコ",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アコ.png",
  },
  ヒマリ: {
    charaName: "ヒマリ",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒマリ.png",
  },
  レイジョ: {
    charaName: "レイジョ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/レイジョ.png",
  },
  ナツ: {
    charaName: "ナツ",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ナツ.png",
  },
  セリカ: {
    charaName: "セリカ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セリカ.png",
  },
  シロコ: {
    charaName: "シロコ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シロコ.png",
  },
  フブキ: {
    charaName: "フブキ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/フブキ.png",
  },
  サオリ: {
    charaName: "サオリ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サオリ.png",
  },
  ユズ: {
    charaName: "ユズ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ユズ.png",
  },
  ウミカ: {
    charaName: "ウミカ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ウミカ.png",
  },
  ノドカ: {
    charaName: "ノドカ",
    equip3: "ネックレス",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ノドカ.png",
  },
  イズミ: {
    charaName: "イズミ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イズミ.png",
  },
  "ミヤコ（水着）": {
    charaName: "ミヤコ（水着）",
    equip3: "お守り",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミヤコ（水着）.png",
  },
  "セリカ（正月）": {
    charaName: "セリカ（正月）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セリカ（正月）.png",
  },
  "ウイ（水着）": {
    charaName: "ウイ（水着）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ウイ（水着）.png",
  },
  キララ: {
    charaName: "キララ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/キララ.png",
  },
  ミサキ: {
    charaName: "ミサキ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミサキ.png",
  },
  "サオリ（水着）": {
    charaName: "サオリ（水着）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サオリ（水着）.png",
  },
  セリナ: {
    charaName: "セリナ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セリナ.png",
  },
  "マリナ（チーパオ）": {
    charaName: "マリナ（チーパオ）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マリナ（チーパオ）.png",
  },
  アリス: {
    charaName: "アリス",
    equip3: "お守り",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アリス.png",
  },
  "シズコ（水着）": {
    charaName: "シズコ（水着）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シズコ（水着）.png",
  },
  "ヒナタ（水着）": {
    charaName: "ヒナタ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒナタ（水着）.png",
  },
  シズコ: {
    charaName: "シズコ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/シズコ.png",
  },
  "ハルナ（体操服）": {
    charaName: "ハルナ（体操服）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハルナ（体操服）.png",
  },
  "ハルナ（正月）": {
    charaName: "ハルナ（正月）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハルナ（正月）.png",
  },
  "ミユ（水着）": {
    charaName: "ミユ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ミユ（水着）.png",
  },
  "キリノ（水着）": {
    charaName: "キリノ（水着）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/キリノ（水着）.png",
  },
  "ヒビキ（応援団）": {
    charaName: "ヒビキ（応援団）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ヒビキ（応援団）.png",
  },
  "チナツ（温泉）": {
    charaName: "チナツ（温泉）",
    equip3: "お守り",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/チナツ（温泉）.png",
  },
  カエデ: {
    charaName: "カエデ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カエデ.png",
  },
  アカネ: {
    charaName: "アカネ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アカネ.png",
  },
  "ツバキ（ガイド）": {
    charaName: "ツバキ（ガイド）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッジ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ツバキ（ガイド）.png",
  },
  "サヤ（私服）": {
    charaName: "サヤ（私服）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サヤ（私服）.png",
  },
  "ノア（パジャマ）": {
    charaName: "ノア（パジャマ）",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ノア（パジャマ）.png",
  },
  "ノノミ（水着）": {
    charaName: "ノノミ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ノノミ（水着）.png",
  },
  "マシロ（水着）": {
    charaName: "マシロ（水着）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マシロ（水着）.png",
  },
  "ハレ（キャンプ）": {
    charaName: "ハレ（キャンプ）",
    equip3: "お守り",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハレ（キャンプ）.png",
  },
  ハナエ: {
    charaName: "ハナエ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ハナエ.png",
  },
  ココナ: {
    charaName: "ココナ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ココナ.png",
  },
  ジュリ: {
    charaName: "ジュリ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/ジュリ.png",
  },
  コユキ: {
    charaName: "コユキ",
    equip3: "腕時計",
    equip1: "グローブ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コユキ.png",
  },
  "マリー（体操服）": {
    charaName: "マリー（体操服）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/マリー（体操服）.png",
  },
  "アカネ（バニーガール）": {
    charaName: "アカネ（バニーガール）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アカネ（バニーガール）.png",
  },
  "アカリ（正月）": {
    charaName: "アカリ（正月）",
    equip3: "腕時計",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アカリ（正月）.png",
  },
  セナ: {
    charaName: "セナ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/セナ.png",
  },
  "コトリ（応援団）": {
    charaName: "コトリ（応援団）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コトリ（応援団）.png",
  },
  コタマ: {
    charaName: "コタマ",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/コタマ.png",
  },
  "カリン（バニーガール）": {
    charaName: "カリン（バニーガール）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/カリン（バニーガール）.png",
  },
  モミジ: {
    charaName: "モミジ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/モミジ.png",
  },
  "イズミ（水着）": {
    charaName: "イズミ（水着）",
    equip3: "ネックレス",
    equip1: "シューズ",
    equip2: "バッグ",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/イズミ（水着）.png",
  },
  サクラコ: {
    charaName: "サクラコ",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/サクラコ.png",
  },
  "アル（ドレス）": {
    charaName: "アル（ドレス）",
    equip3: "ネックレス",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アル（ドレス）.png",
  },
  "アリス（メイド）": {
    charaName: "アリス（メイド）",
    equip3: "腕時計",
    equip1: "帽子",
    equip2: "ヘアピン",
    imgUrl: "https://assets.nu-lo.com/bluearchive/characters/アリス（メイド）.png",
  },
};
