import { EquipGrind } from "@/types/ba-equip-grind";
// WARNING 周回エリアが増えたら変更
export const EQUIPS_GRINDS: EquipGrind[] = [
  {
    areaName: "2-1",
    first: "ヘアピン",
    second: "バッジ",
    third: "腕時計",
    tier: 1,
  },
  {
    areaName: "2-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "ネックレス",
    tier: 1,
  },
  {
    areaName: "2-3",
    first: "お守り",
    second: "腕時計",
    third: "ヘアピン",
    tier: 1,
  },
  {
    areaName: "2-4",
    first: "腕時計",
    second: "お守り",
    third: "ネックレス",
    tier: 1,
  },
  {
    areaName: "2-5",
    first: "ネックレス",
    second: "バッジ",
    third: "お守り",
    tier: 1,
  },
  {
    areaName: "4-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 2,
  },
  {
    areaName: "4-2",
    first: "グローブ",
    second: "バッグ",
    third: "帽子",
    tier: 2,
  },
  {
    areaName: "4-3",
    first: "シューズ",
    second: "帽子",
    third: "グローブ",
    tier: 2,
  },
  {
    areaName: "4-4",
    first: "バッグ",
    second: "シューズ",
    third: "ヘアピン",
    tier: 2,
  },
  {
    areaName: "4-5",
    first: "バッジ",
    second: "バッグ",
    third: "帽子",
    tier: 2,
  },
  {
    areaName: "5-1",
    first: "ヘアピン",
    second: "バッジ",
    third: "腕時計",
    tier: 2,
  },
  {
    areaName: "5-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "ネックレス",
    tier: 2,
  },
  {
    areaName: "5-3",
    first: "お守り",
    second: "腕時計",
    third: "ヘアピン",
    tier: 2,
  },
  {
    areaName: "5-4",
    first: "腕時計",
    second: "お守り",
    third: "ネックレス",
    tier: 2,
  },
  {
    areaName: "5-5",
    first: "ネックレス",
    second: "バッジ",
    third: "お守り",
    tier: 2,
  },
  {
    areaName: "7-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 3,
  },
  {
    areaName: "7-2",
    first: "グローブ",
    second: "バッグ",
    third: "帽子",
    tier: 3,
  },
  {
    areaName: "7-3",
    first: "シューズ",
    second: "帽子",
    third: "グローブ",
    tier: 3,
  },
  {
    areaName: "7-4",
    first: "バッグ",
    second: "シューズ",
    third: "ヘアピン",
    tier: 3,
  },
  {
    areaName: "7-5",
    first: "バッジ",
    second: "バッグ",
    third: "帽子",
    tier: 3,
  },
  {
    areaName: "8-1",
    first: "ヘアピン",
    second: "バッジ",
    third: "腕時計",
    tier: 3,
  },
  {
    areaName: "8-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "ネックレス",
    tier: 3,
  },
  {
    areaName: "8-3",
    first: "お守り",
    second: "腕時計",
    third: "ヘアピン",
    tier: 3,
  },
  {
    areaName: "8-4",
    first: "腕時計",
    second: "お守り",
    third: "ネックレス",
    tier: 3,
  },
  {
    areaName: "8-5",
    first: "ネックレス",
    second: "バッジ",
    third: "お守り",
    tier: 3,
  },
  {
    areaName: "10-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 4,
  },
  {
    areaName: "10-2",
    first: "グローブ",
    second: "バッグ",
    third: "帽子",
    tier: 4,
  },
  {
    areaName: "10-3",
    first: "シューズ",
    second: "帽子",
    third: "グローブ",
    tier: 4,
  },
  {
    areaName: "10-4",
    first: "バッグ",
    second: "シューズ",
    third: "ヘアピン",
    tier: 4,
  },
  {
    areaName: "10-5",
    first: "バッジ",
    second: "バッグ",
    third: "帽子",
    tier: 4,
  },
  {
    areaName: "11-1",
    first: "ヘアピン",
    second: "バッジ",
    third: "腕時計",
    tier: 4,
  },
  {
    areaName: "11-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "ネックレス",
    tier: 4,
  },
  {
    areaName: "11-3",
    first: "お守り",
    second: "腕時計",
    third: "ヘアピン",
    tier: 4,
  },
  {
    areaName: "11-4",
    first: "腕時計",
    second: "お守り",
    third: "ネックレス",
    tier: 4,
  },
  {
    areaName: "11-5",
    first: "ネックレス",
    second: "バッジ",
    third: "お守り",
    tier: 4,
  },
  {
    areaName: "13-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 5,
  },
  {
    areaName: "13-2",
    first: "グローブ",
    second: "バッジ",
    third: "帽子",
    tier: 5,
  },
  {
    areaName: "13-3",
    first: "シューズ",
    second: "帽子",
    third: "ヘアピン",
    tier: 5,
  },
  {
    areaName: "13-4",
    first: "ヘアピン",
    second: "シューズ",
    third: "バッグ",
    tier: 5,
  },
  {
    areaName: "13-5",
    first: "バッジ",
    second: "グローブ",
    third: "帽子",
    tier: 5,
  },
  {
    areaName: "14-1",
    first: "お守り",
    second: "ネックレス",
    third: "腕時計",
    tier: 5,
  },
  {
    areaName: "14-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "お守り",
    tier: 5,
  },
  {
    areaName: "14-3",
    first: "バッグ",
    second: "ネックレス",
    third: "腕時計",
    tier: 5,
  },
  {
    areaName: "14-4",
    first: "腕時計",
    second: "お守り",
    third: "バッジ",
    tier: 5,
  },
  {
    areaName: "14-5",
    first: "ネックレス",
    second: "ヘアピン",
    third: "バッグ",
    tier: 5,
  },
  {
    areaName: "16-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 6,
  },
  {
    areaName: "16-2",
    first: "グローブ",
    second: "バッジ",
    third: "帽子",
    tier: 6,
  },
  {
    areaName: "16-3",
    first: "シューズ",
    second: "帽子",
    third: "ヘアピン",
    tier: 6,
  },
  {
    areaName: "16-4",
    first: "ヘアピン",
    second: "シューズ",
    third: "バッグ",
    tier: 6,
  },
  {
    areaName: "16-5",
    first: "バッジ",
    second: "グローブ",
    third: "帽子",
    tier: 6,
  },
  {
    areaName: "17-1",
    first: "お守り",
    second: "ネックレス",
    third: "腕時計",
    tier: 6,
  },
  {
    areaName: "17-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "お守り",
    tier: 6,
  },
  {
    areaName: "17-3",
    first: "バッグ",
    second: "ネックレス",
    third: "腕時計",
    tier: 6,
  },
  {
    areaName: "17-4",
    first: "腕時計",
    second: "お守り",
    third: "バッジ",
    tier: 6,
  },
  {
    areaName: "17-5",
    first: "ネックレス",
    second: "ヘアピン",
    third: "バッグ",
    tier: 6,
  },
  {
    areaName: "19-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 7,
  },
  {
    areaName: "19-2",
    first: "グローブ",
    second: "バッジ",
    third: "帽子",
    tier: 7,
  },
  {
    areaName: "19-3",
    first: "シューズ",
    second: "帽子",
    third: "ヘアピン",
    tier: 7,
  },
  {
    areaName: "19-4",
    first: "ヘアピン",
    second: "シューズ",
    third: "バッグ",
    tier: 7,
  },
  {
    areaName: "19-5",
    first: "バッジ",
    second: "グローブ",
    third: "帽子",
    tier: 7,
  },
  {
    areaName: "20-1",
    first: "お守り",
    second: "ネックレス",
    third: "腕時計",
    tier: 7,
  },
  {
    areaName: "20-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "お守り",
    tier: 7,
  },
  {
    areaName: "20-3",
    first: "バッグ",
    second: "ネックレス",
    third: "腕時計",
    tier: 7,
  },
  {
    areaName: "20-4",
    first: "腕時計",
    second: "お守り",
    third: "バッジ",
    tier: 7,
  },
  {
    areaName: "20-5",
    first: "ネックレス",
    second: "ヘアピン",
    third: "バッグ",
    tier: 7,
  },
  {
    areaName: "22-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 8,
  },
  {
    areaName: "22-2",
    first: "グローブ",
    second: "バッジ",
    third: "帽子",
    tier: 8,
  },
  {
    areaName: "22-3",
    first: "シューズ",
    second: "帽子",
    third: "ヘアピン",
    tier: 8,
  },
  {
    areaName: "22-4",
    first: "ヘアピン",
    second: "シューズ",
    third: "バッグ",
    tier: 8,
  },
  {
    areaName: "22-5",
    first: "バッジ",
    second: "グローブ",
    third: "帽子",
    tier: 8,
  },
  {
    areaName: "23-1",
    first: "お守り",
    second: "ネックレス",
    third: "腕時計",
    tier: 8,
  },
  {
    areaName: "23-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "お守り",
    tier: 8,
  },
  {
    areaName: "23-3",
    first: "バッグ",
    second: "ネックレス",
    third: "腕時計",
    tier: 8,
  },
  {
    areaName: "23-4",
    first: "腕時計",
    second: "お守り",
    third: "バッジ",
    tier: 8,
  },
  {
    areaName: "23-5",
    first: "ネックレス",
    second: "ヘアピン",
    third: "バッグ",
    tier: 8,
  },
  {
    areaName: "25-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 9,
  },
  {
    areaName: "25-2",
    first: "グローブ",
    second: "バッジ",
    third: "帽子",
    tier: 9,
  },
  {
    areaName: "25-3",
    first: "シューズ",
    second: "帽子",
    third: "ヘアピン",
    tier: 9,
  },
  {
    areaName: "25-4",
    first: "ヘアピン",
    second: "バッジ",
    third: "バッグ",
    tier: 9,
  },
  {
    areaName: "25-5",
    first: "バッジ",
    second: "グローブ",
    third: "帽子",
    tier: 9,
  },
  {
    areaName: "26-1",
    first: "お守り",
    second: "ネックレス",
    third: "腕時計",
    tier: 9,
  },
  {
    areaName: "26-2",
    first: "ヘアピン",
    second: "腕時計",
    third: "シューズ",
    tier: 9,
  },
  {
    areaName: "26-3",
    first: "バッグ",
    second: "お守り",
    third: "腕時計",
    tier: 9,
  },
  {
    areaName: "26-4",
    first: "腕時計",
    second: "グローブ",
    third: "バッジ",
    tier: 9,
  },
  {
    areaName: "26-5",
    first: "ネックレス",
    second: "ヘアピン",
    third: "バッグ",
    tier: 9,
  },
  {
    areaName: "27-1",
    first: "帽子",
    second: "グローブ",
    third: "シューズ",
    tier: 10,
  },
];
